"""C1 contract checks and a small, generated Markdown validation report."""

from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


ERROR_FLAGS = {"ref_unresolved", "ref_malformed", "time_invalid", "type_unavailable"}
C1_FIELDS = (
    "seg_id",
    "meeting",
    "agent",
    "channel",
    "speaker_id",
    "src_start",
    "src_end",
    "start",
    "end",
    "timing_method",
    "position",
    "source_da_id",
    "element_ordinal",
    "part_index",
    "n_parts",
    "raw_type",
    "original_type",
    "part_type",
    "adjacency_raw",
    "comment",
    "text",
    "words",
    "quality_flags",
)


def validate_rows(rows: list[dict[str, Any]]) -> list[str]:
    """Return contract violations. Error flags are reported separately, not erased."""
    problems: list[str] = []
    segment_ids = [row["seg_id"] for row in rows]
    if len(segment_ids) != len(set(segment_ids)):
        problems.append("seg_id values are not unique")

    positions_by_meeting: dict[str, list[int]] = defaultdict(list)
    parts_by_element: dict[tuple[str, str], list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        if tuple(row) != C1_FIELDS:
            problems.append(f"{row['source_da_id']}: C1 field order does not match the schema")
        positions_by_meeting[row["meeting"]].append(row["position"])
        parts_by_element[(row["meeting"], row["source_da_id"])].append(row)
        if not (row["src_start"] <= row["start"] <= row["end"] <= row["src_end"]):
            problems.append(f"{row['source_da_id']}: derived timing is outside source timing")

    for meeting, positions in positions_by_meeting.items():
        if positions != list(range(len(positions))):
            problems.append(f"{meeting}: positions are not contiguous from zero")
    for source_key, parts in parts_by_element.items():
        ordered_parts = sorted(parts, key=lambda row: row["part_index"])
        for left, right in zip(ordered_parts, ordered_parts[1:]):
            if left["end"] > right["start"]:
                problems.append(f"{source_key[1]}: split-part timings overlap")
    return problems


def write_validation_report(
    report_path: Path,
    rows: list[dict[str, Any]],
    source_counts: Counter[str],
    transcript_problems: list[dict[str, str]],
    contract_problems: list[str],
) -> None:
    """Write a deterministic report from measured parser results."""
    flags = Counter(flag for row in rows for flag in row["quality_flags"])
    rows_by_parts = Counter(row["n_parts"] for row in rows)
    error_sources = {
        row["source_da_id"]: tuple(sorted(ERROR_FLAGS.intersection(row["quality_flags"])))
        for row in rows
        if ERROR_FLAGS.intersection(row["quality_flags"])
    }
    unresolved_reasons = Counter(problem["reason"] for problem in transcript_problems)
    lines = [
        "# NXT C1 parse validation",
        "",
        "This report is generated by `scripts/parse_nxt.py`; counts are measured, not hard-coded.",
        "",
        "## Source structure",
        "",
        f"- Dialogue-act files: {source_counts['dialogue_act_files']}",
        f"- Meetings: {source_counts['meetings']}",
        f"- Dialogue-act elements: {source_counts['dialogue_act_elements']}",
        f"- Generated C1 rows: {len(rows)}",
        f"- Independent pipe-part count: {source_counts['independent_pipe_parts']}",
        f"- Reconciliation: {'matches' if len(rows) == source_counts['independent_pipe_parts'] else 'DIFFERS'}.",
        "",
        "## Rows by number of pipe parts",
        "",
    ]
    for part_count, count in sorted(rows_by_parts.items()):
        lines.append(f"- {part_count} part(s): {count}")
    lines += ["", "## Quality flags", ""]
    if flags:
        lines += [
            f"- `{flag}`: {count}"
            for flag, count in sorted(flags.items())
        ]
    else:
        lines.append("- None")
    lines.append(f"- Error-class source dialogue acts: {len(error_sources)}")
    lines += [
        "",
        "## Contract checks",
        "",
        (
            "- Timing, ID, ordering and field-order checks: "
            f"{'passed' if not contract_problems else 'FAILED'}."
        ),
        (
            "- Transcript split alignment: "
            f"{'passed' if not transcript_problems else 'FAILED'}."
        ),
        "- Table 5 comparison: pending; Table 5 is not available in this repository.",
    ]
    if contract_problems:
        lines += ["", "### Contract failures", ""]
        for problem in contract_problems:
            lines.append(f"- {problem}")
    if error_sources:
        lines += ["", "### Error-class rows", ""]
        lines += [
            f"- `{source_da_id}`: {', '.join(flags)}"
            for source_da_id, flags in sorted(error_sources.items())
        ]
    if transcript_problems:
        lines += ["", "### Unresolved source summary", ""]
        lines += [
            f"- {reason}: {count}"
            for reason, count in sorted(unresolved_reasons.items())
        ]
        lines += ["", "### Unresolved transcript boundaries", ""]
        lines += [
            f"- `{problem['source_da_id']}`: {problem['reason']} ({problem['context']})"
            for problem in transcript_problems
        ]
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
