"""Drop non-speech, unlabelled and empty rows from the annotated output and keep the links consistent."""

from collections import Counter
from collections.abc import Sequence
from typing import Final, cast

from smi.data.annotate.contract import Findings, check_links
from smi.data.annotate.links.proposals import NO_PAIR, OK
from smi.data.annotate.records import AnnotatedRow, LinkRecord, ParsedRow

DROP_FLAGS: Final[tuple[str, ...]] = ("is_nonspeech", "is_nonlabeled", "is_empty")


class CleanedRow(ParsedRow):
    """An annotated row without the three drop flags, which would all be false after cleaning."""

    label: str
    label_bk_merged: str
    target_tags: list[str]
    is_multi_target: bool
    is_layer2_proposal: bool
    general_tags: list[str]
    disruption_markers: list[str]


_CLEANED_KEYS: Final = tuple(CleanedRow.__annotations__)


def is_dropped(row: AnnotatedRow) -> bool:
    return any(row[flag] for flag in DROP_FLAGS)


def clean_rows(annotated: Sequence[AnnotatedRow]) -> list[CleanedRow]:
    return [
        cast(CleanedRow, {key: row[key] for key in _CLEANED_KEYS})
        for row in annotated
        if not is_dropped(row)
    ]


def clean_links(links: Sequence[LinkRecord], annotated: Sequence[AnnotatedRow]) -> list[LinkRecord]:
    dropped = {row["seg_id"] for row in annotated if is_dropped(row)}
    return [_prune(link, dropped) for link in links if link["proposal_id"] not in dropped]


def _prune(link: LinkRecord, dropped: set[str]) -> LinkRecord:
    chains = [kept for chain in link["responder_chains"] if (kept := [s for s in chain if s not in dropped])]
    status = NO_PAIR if link["status"] == OK and not chains else link["status"]
    return {**link, "responder_chains": chains, "has_response": bool(chains), "status": status}


def check_cleaned(
    annotated: Sequence[AnnotatedRow],
    annotated_links: Sequence[LinkRecord],
    cleaned: Sequence[CleanedRow],
    cleaned_links: Sequence[LinkRecord],
) -> list[str]:
    expected = [row for row in annotated if not is_dropped(row)]
    if len(cleaned) != len(expected):
        return [f"row count is {len(cleaned)}, expected {len(expected)} (annotated minus dropped)"]
    findings = Findings()
    for before, after in zip(expected, cleaned):
        for problem in _row_problems(before, after):
            findings.add(problem, after["seg_id"])
    return [
        *findings.messages(),
        *check_links(cleaned, cleaned_links),
        *_link_problems(annotated, annotated_links, cleaned_links),
    ]


def _row_problems(before: AnnotatedRow, after: CleanedRow) -> list[str]:
    if tuple(after) != _CLEANED_KEYS:
        return ["key order differs from CleanedRow"]
    unchanged = all(after[key] == before[key] for key in _CLEANED_KEYS)
    return [] if unchanged else ["a field was changed (position and seg_id must stay as annotated)"]


def _link_problems(
    annotated: Sequence[AnnotatedRow], annotated_links: Sequence[LinkRecord], cleaned_links: Sequence[LinkRecord]
) -> list[str]:
    dropped = {row["seg_id"] for row in annotated if is_dropped(row)}
    expected = [link for link in annotated_links if link["proposal_id"] not in dropped]
    if [link["proposal_id"] for link in cleaned_links] != [link["proposal_id"] for link in expected]:
        return ["cleaned links are not the annotated links minus dropped proposals"]
    findings = Findings()
    for before, after in zip(expected, cleaned_links):
        record_id = after["proposal_id"]
        if (before["adjacency_tokens"], before["pair_group"]) != (after["adjacency_tokens"], after["pair_group"]):
            findings.add("adjacency_tokens or pair_group changed", record_id)
        kept = [s for chain in before["responder_chains"] for s in chain if s not in dropped]
        if kept != [s for chain in after["responder_chains"] for s in chain]:
            findings.add("chains differ from the annotated chains minus dropped rows", record_id)
    return findings.messages()


def build_cleaning_report(
    annotated: Sequence[AnnotatedRow],
    annotated_links: Sequence[LinkRecord],
    cleaned: Sequence[CleanedRow],
    cleaned_links: Sequence[LinkRecord],
) -> str:
    labels_before = Counter(row["label"] for row in annotated)
    labels_after = Counter(row["label"] for row in cleaned)
    status_before = Counter(link["status"] for link in annotated_links)
    status_after = Counter(link["status"] for link in cleaned_links)
    touched = sum(
        sum(map(len, a["responder_chains"])) != sum(map(len, b["responder_chains"]))
        for a, b in zip(annotated_links, cleaned_links)
    )
    lines = [
        "# Cleaning report", "",
        "Generated by `scripts/clean_rows.py`; counts are measured, not hard-coded.", "",
        "## Rows", "",
        f"- Annotated rows: {len(annotated)}",
        f"- Dropped rows: {len(annotated) - len(cleaned)}",
        f"- Cleaned rows: {len(cleaned)}",
        "- `seg_id` and `position` are unchanged, so `position` has gaps where rows were dropped.", "",
        "| Reason | Rows |", "|---|---|",
        *(f"| {flag} | {sum(row[flag] for row in annotated)} |" for flag in DROP_FLAGS),
        "",
        "A row can have more than one reason, so the reasons add up to more than the dropped total.", "",
        "## Rows by label", "",
        "| Label | Before | After |", "|---|---|---|",
        *(f"| {label} | {labels_before[label]} | {labels_after[label]} |" for label in sorted(labels_before)),
        "", "## Links", "",
        f"- Link records: {len(annotated_links)} before, {len(cleaned_links)} after",
        f"- Records that lost at least one reply row: {touched}", "",
        "| Status | Before | After |", "|---|---|---|",
        *(f"| {s} | {status_before[s]} | {status_after[s]} |" for s in sorted(status_before | status_after)),
    ]
    return "\n".join(lines) + "\n"
