"""Build the Markdown annotation report from the annotated rows, links and group audit notes."""

from collections import Counter
from collections.abc import Iterable, Sequence
from typing import Final

from smi import labels
from smi.data.annotate.links.proposals import AMBIGUOUS, MALFORMED, NO_PAIR, OK
from smi.data.annotate.records import AnnotatedRow, LinkRecord
from smi.data.annotate.rows import ERROR_FLAGS

SPEC_MULTI_TARGET: Final = 18  
WINDOW: Final = 5

_NEAR: Final = f"1-{WINDOW}"
_DISTANCE_LIMITS: Final = ((WINDOW, _NEAR), (10, f"{WINDOW + 1}-10"), (50, "11-50"))
_FAR: Final = "more than 50"
_NONE: Final = "no response after the proposal"
_DISTANCE_BUCKETS: Final = (*(name for _, name in _DISTANCE_LIMITS), _FAR, _NONE)


def build_report(
    annotated: Sequence[AnnotatedRow], links: Sequence[LinkRecord], notes: Counter[str]
) -> str:
    sections = (
        ["# Annotation report", "", "Generated by `scripts/annotate_rows.py`", ""],
        _rows_section(annotated),
        _links_section(links),
        _notes_section(notes),
        _reachability_section(annotated, links),
    )
    return "\n".join(line for section in sections for line in section) + "\n"


def _rows_section(annotated: Sequence[AnnotatedRow]) -> list[str]:
    label_counts = Counter(row["label"] for row in annotated)
    multi = [row for row in annotated if row["is_multi_target"]]
    verdict = "matches" if len(multi) == SPEC_MULTI_TARGET else "differs from"
    flag_counts = [
        (name, sum(row[name] for row in annotated))
        for name in ("is_layer2_proposal", "is_nonspeech", "is_nonlabeled", "is_empty")
    ]
    with_error = sum(not ERROR_FLAGS.isdisjoint(row["quality_flags"]) for row in annotated)
    combos = Counter(tuple(row["target_tags"]) for row in multi)
    return [
        "## Rows", "",
        f"- Annotated rows: {len(annotated)}",
        f"- Rows whose label changes under the b/bk variant: "
        f"{sum(row['label'] != row['label_bk_merged'] for row in annotated)}",
        f"- Rows carrying an error-class quality flag: {with_error}",
        "",
        "### Labels", "",
        *_table(("Label", "Rows"), [(label, label_counts[label]) for label in labels.LABELS]),
        "",
        "### Flags", "",
        *_table(("Flag", "Rows"), flag_counts),
        "",
        "### Rows with two or more target tags", "",
        f"- {len(multi)} rows; the spec expects {SPEC_MULTI_TARGET} ({verdict} the spec).",
        "",
        *_table(("Target tags", "Rows"), [(", ".join(tags), n) for tags, n in sorted(combos.items())]),
        "",
    ]


def _links_section(links: Sequence[LinkRecord]) -> list[str]:
    status_counts = Counter(link["status"] for link in links)
    chain_counts = Counter(len(link["responder_chains"]) for link in links if link["status"] == OK)
    return [
        "## Links", "",
        f"- Link records (one per Layer-2 proposal row): {len(links)}",
        "",
        *_table(("Status", "Records"), [(s, status_counts[s]) for s in (OK, NO_PAIR, MALFORMED, AMBIGUOUS)]),
        "",
        "### Responder chains per `ok` record", "",
        *_table(("Chains", "Records"), sorted(chain_counts.items())),
        "",
    ]


def _notes_section(notes: Counter[str]) -> list[str]:
    return [
        "## Pair-group audit notes", "",
        "Counted while building pair groups; unmatched responses are deliberately not attached.",
        "",
        *_table(("Note", "Count"), sorted(notes.items())),
        "",
    ]


def _reachability_section(annotated: Sequence[AnnotatedRow], links: Sequence[LinkRecord]) -> list[str]:
    position_of = {row["seg_id"]: row["position"] for row in annotated}
    ok_links = [link for link in links if link["status"] == OK]
    buckets = Counter(_bucket(_nearest_after(link, position_of)) for link in ok_links)
    reachable = buckets[_NEAR]
    share = f"{100 * reachable / len(ok_links):.1f}%" if ok_links else "n/a"
    return [
        "## Response distance (informational)", "",
        f"For each `ok` proposal, the distance in rows (by `position`, every row counted) from the "
        f"proposal to the nearest first response segment after it. A link model that looks at the next "
        f"{WINDOW} rows can reach {reachable} of {len(ok_links)} ({share}).",
        "",
        *_table(("Distance in rows", "Proposals"), [(b, buckets[b]) for b in _DISTANCE_BUCKETS]),
        "",
    ]


def _nearest_after(link: LinkRecord, position_of: dict[str, int]) -> int | None:
    start = position_of[link["proposal_id"]]
    after = [position_of[chain[0]] - start for chain in link["responder_chains"] if position_of[chain[0]] > start]
    return min(after, default=None)


def _bucket(distance: int | None) -> str:
    if distance is None:
        return _NONE
    return next((name for limit, name in _DISTANCE_LIMITS if distance <= limit), _FAR)


def _table(headers: tuple[str, str], rows: Iterable[tuple[object, object]]) -> list[str]:
    return [f"| {headers[0]} | {headers[1]} |", "|---|---|", *(f"| {a} | {b} |" for a, b in rows)]
